import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import '@/styles/header.css';
import Providers from '@/components/Providers';
import AppShell from '@/components/layout/app-shell';
import Footer from '@/components/layout/footer';
import HeaderTW from '@/components/layout/header-tw';
import SonnerClient from '@/components/ui/sonner-client';
import MotionProvider from '@/components/motion/motion-provider';
import LayoutClient from './layout-client';

const montserrat = Montserrat({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fr" className="dark">
      <head>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
      </head>
      <body className={montserrat.variable}>
        <Providers>
          <MotionProvider>
            <LayoutClient>
              <AppShell topbar={<HeaderTW/>} footer={<Footer />}>{children}</AppShell>
            </LayoutClient>
          </MotionProvider>
          <SonnerClient />
        </Providers>
      </body>
    </html>
  );
}
